services:
  jenkins_pydock:
    image: jpydock
    container_name: jpydock
    restart: unless-stopped
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=jpydock
      - JENKINS_SECRET=3fb4fc54731917754cfe9314d25ef345896b0ac0939ea7fbdcfca31007e3401f
      - JENKINS_AGENT_WORKDIR=/home/jenkins/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins_pytest:
    image: jpytest
    container_name: jpytest
    restart: unless-stopped
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=jpytest
      - JENKINS_SECRET=fb71574dda9a8c78ec447ce25f00c54919fb88469fc288003b01a2cd871195ad
      - JENKINS_AGENT_WORKDIR=/home/jenkins/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../jenkinsvol:/var/jenkins_home
    restart: unless-stopped
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
 